include("anneal_test.jl")
include("ANOVA_test.jl")
include("archimedes_test.jl")
include("babylonian_test.jl")
include("binarysearch_test.jl")
include("bisect_test.jl")
include("cholesky_test.jl")
include("conjugategradients_test.jl")
