__precompile__()

module AlgorithmsFromTheBook

include("anneal.jl")
include("ANOVA.jl")
include("archimedes.jl")
include("babylonian.jl")
include("binarysearch.jl")
include("bisect.jl")
include("cholesky.jl")
include("conjugategradients.jl")
include("connect.jl")
include("convolve.jl")
include("cosine_min.jl")
include("deviate_discrete.jl")
include("deviate_gamma.jl")
include("deviate_normal.jl")
include("deviate_poisson.jl")
include("deviate_uniform.jl")
include("deviate_zipf.jl")
include("dijkstra.jl")
include("dirichlet.jl")
include("easysvd.jl")
include("emcluster.jl")
include("eratosthenes.jl")
include("euclid.jl")
include("fastlog.jl")
include("fft.jl")
include("gauss.jl")
include("gram_schmidt.jl")
include("heapsort.jl")
include("householder.jl")
include("jacobi.jl")
include("kmeans.jl")

end
